services:
  pikabu-bot:
    build: .
    container_name: pikabu-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/data/bot.db
